services:
  users:
    container_name: users-ms
    build:
      context: ./users-ms
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./users-ms:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=users_db
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: npm run start:dev

  postgres:
    container_name: users_postgres_db
    image: postgres:15.3-alpine
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: